### ISSUE TITLE
Use cloud identity API to get group membership to avoid UNKNOWN_INFO_DENIED

### ISSUE THREAD

**Issue by kbroughton** [googleapis/python-policy-troubleshooter#75]
This is a feature request related to the permissions required to determine if a user can do a thing.
It is google's promoted best practice to assign users to groups to grant permissions, but support for group membership calculations currently requires a custom admin group.

"To allow a user who is not a Super or Group admin to troubleshoot access, create a custom Google Workspace administrator role that contains the groups.read privilege (located under Admin API Privileges) and grant it to the user."
- https://cloud.google.com/iam/docs/troubleshooting-access

 **Describe the solution you'd like**
Since Google Workspace Admin is usually a separate function from GCP admins, it would be nice if Troubleshooter could support group membership without this additional privilege.

I believe there is a way to do this using `gcloud identity groups` commands.

    gcloud identity groups  memberships get-membership-graph \
      --member-email user@example.com 
      --labels="cloudidentity.googleapis.com/groups.discussion_forum"`
  
    ERROR: (gcloud.identity.groups.memberships.get-membership-graph) User [engineer@example.com] does not 
    have permission to access groups instance [-] (or it may not exist): Error(4016): Insufficient permissions to retrieve 
    membership graph.

However, with the following permission grant, I can check group membership of the desired principal.

    gcloud organizations add-iam-policy-binding --role roles/identityplatform.viewer \ 
        --member group:security-engineering@example.com $ORG_ID

     gcloud identity groups memberships  check-transitive-membership \
        --group-email security-engineering@example.com --member-email user@example.com
    hasMembership: true

With my current permissions, I can run Troubleshooter AND get the necessary group info required using cloud identity groups. It seems Troubleshooter could use this info in its calculations and avoid the need to require a custom group on Google Workspaces.
 

**Describe alternatives you've considered**

The easiest alternative would be for GCP to support group emails as principals.
I considered supplying the group memberships manually, but Troubleshooter doesn't support groups
$ gcloud policy-troubleshoot iam --permission container.bindings.list --principal-email group1@example.com //container.googleapis.com/projects/development-proj/clusters/cluster1
ERROR: (gcloud.policy-troubleshoot.iam) INVALID_ARGUMENT: group principal is unsupported
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: UNSUPPORTED_PRINCIPAL_GROUP
    field: accessTuple.principal

 **Additional context**
Ths issue came from trying to answer simple questions about who has access to what and why. Troubleshooter is a great tool, but all really only is useful if you have group info as well.

**Comment by parthea** [comment]
Googlers see b/278351350 for the internal feature request. I'm going to close this issue as the feature request has been passed along to the API team.
